enum Tool {
  ArtisansTools = "artisan's tools",
  AlchemistsSupplies = "alchemist's supplies",
  BrewersSupplies = "brewer's supplies",
  CalligraphersSupplies = "calligrapher's supplies",
  CarpentersTools = "carpenter's tools",
  CartographersTools = "cartographer's tools",
  CobblersTools = "cobbler's tools",
  CooksUtensils = "cook's utensils",
  GlassblowersTools = "glassblower's tools",
  JewelersTools = "jeweler's tools",
  LeatherworkersTools = "leatherworker's tools",
  MasonsTools = "mason's tools",
  PaintersSupplies = "painter's supplies",
  PottersTools = "potter's tools",
  SmithsTools = "smith's tools",
  TinkersTools = "tinker's tools",
  WeaverTools = "weaver's tools",
  WoodcarversTools = "woodcarver's tools",
  DisquiseKit = "disguise kit",
  ForgeryKit = "forgery kit",
  GamingSet = "gaming set",
  HerbalismKit = "herbalism kit",
  MusicalInstrument = "musical instrument",
  NavigatorsTools = "navigator's tools",
  ThievesTools = "thieves' tools",
  VehiclesLand = "vehicles (land)",
  VehiclesWater = "vehicles (water)",
  VehiclesAir = "vehicles (air)",
}

export default Tool;
