enum LanguageEnum {
  Abyssal = "Abyssal",
  Aquan = "Aquan",
  Auran = "Auran",
  Common = "Common",
  Celestial = "Celestial",
  CantSpeakKnownLanguage = "Can't Speak Known Language",
  Dwarvish = "Dwarvish",
  Draconic = "Draconic",
  DeepSpeech = "Deep Speech",
  Druidic = "Druidic",
  Elvish = "Elvish",
  Gnomish = "Gnomish",
  Giant = "Giant",
  Goblin = "Goblin",
  Gith = "Gith",
  Halfling = "Halfling",
  Infernal = "Infernal",
  Ignan = "Ignan",
  LanguagesKnownInLife = "Languages Known in Life",
  None = "None",
  Orc = "Orc",
  Other = "Other",
  Primordial = "Primordial",
  Sylvan = "Sylvan",
  Terran = "Terran",
  ThievesCant = "Thieve's Cant",
  Telepath = "Telepath",
  Undercommon = "Undercommon",
  AnyChoose = "Any (Choose)",
  All = "All",
}

type Language = LanguageEnum | string;

export default Language;
